Repository EyeSeeTea/d2-reports, pull requests merged in 2023-08, with the labels that each got.

#110 fix: change audit filters title
  i18n/en.pot
  i18n/es.po
  src/webapp/reports/csy-audit-emergency/CSYAuditEmergencyReport.tsx
  src/webapp/reports/csy-audit-trauma/CSYAuditTraumaReport.tsx
Labels: small, waiting-for-review

#107 Feat/glass ear report
  i18n/en.pot
  i18n/es.po
  package.json
  src/compositionRoot.ts
  src/data/common/clients/storage/Namespaces.ts
  src/data/reports/glass-data-submission/GLASSDataSubmissionDefaultRepository.ts
  src/domain/reports/glass-data-submission/entities/GLASSDataSubmissionItem.ts
  src/domain/reports/glass-data-submission/repositories/GLASSDataSubmissionRepository.tsx
  src/domain/reports/glass-data-submission/usecases/GetEARDataSubmissionUseCase.ts
  src/domain/reports/glass-data-submission/usecases/GetGLASSUserPermissionsUseCase.ts
  src/domain/reports/glass-data-submission/usecases/UpdateGLASSSubmissionUseCase.ts
  src/webapp/reports/glass-data-submission/DataSubmissionViewModel.ts
  src/webapp/reports/glass-data-submission/glass-data-submission-list/DataSubmissionList.tsx
  src/webapp/reports/glass-data-submission/glass-data-submission-list/Filters.tsx
Labels: large, waiting-for-review

#113 Feat/adapt monitoring datastore
  src/compositionRoot.ts
  src/data/reports/mal-data-approval/MalDataApprovalDefaultRepository.ts
  src/domain/reports/mal-data-approval/entities/MalDataApprovalItem.ts
  src/domain/reports/mal-data-approval/repositories/MalDataApprovalRepository.ts
  src/domain/reports/mal-data-approval/usecases/GetMalCountryCodesUseCase.ts
  src/domain/reports/mal-data-approval/usecases/GetMonitoringUseCase.ts
  src/domain/reports/mal-data-approval/usecases/SaveMonitoringUseCase.ts
  src/domain/reports/mal-data-approval/usecases/UpdateMalApprovalStatusUseCase.ts
  src/webapp/reports/mal-data-approval/DataApprovalViewModel.ts
  src/webapp/reports/mal-data-approval/data-approval-list/DataApprovalList.tsx
Labels: medium, waiting-for-review

#70 Feat/data quality report
  i18n/en.pot
  i18n/es.po
  src/compositionRoot.ts
  src/data/common/clients/storage/Namespaces.ts
  src/data/reports/data-quality/DataQualityDefaultRepository.ts
  src/domain/reports/data-quality/entities/DataQualityItem.ts
  src/domain/reports/data-quality/repositories/DataQualityRepository.ts
  src/domain/reports/data-quality/usecases/GetDataQualityColumnsUseCase.ts
  src/domain/reports/data-quality/usecases/GetIndicatorsUseCase.ts
  src/domain/reports/data-quality/usecases/GetProgramIndicatorsUseCase.ts
  src/domain/reports/data-quality/usecases/ResetDataQualityValidation.ts
  src/domain/reports/data-quality/usecases/SaveDataQualityColumnsUseCase.ts
  src/domain/reports/data-quality/usecases/SaveDataQualityUseCase.ts
  src/domain/reports/data-quality/usecases/loadDataQualityValidation.ts
  src/index.tsx
  src/webapp/components/reload_warning/ReloadWarningModal.tsx
  src/webapp/reports/Reports.tsx
  src/webapp/reports/data-quality/DataQualityList.tsx
  src/webapp/reports/data-quality/DataQualityReport.tsx
  src/webapp/reports/data-quality/DataQualityViewModel.ts
Labels: large

#114 feat: get dataSubmissionPeriod property from dataStore
  src/data/reports/glass-data-submission/GLASSDataSubmissionDefaultRepository.ts
  src/domain/reports/glass-data-submission/entities/GLASSDataSubmissionItem.ts
  src/domain/reports/glass-data-submission/repositories/GLASSDataSubmissionRepository.tsx
  src/webapp/reports/glass-data-submission/DataSubmissionViewModel.ts
  src/webapp/reports/glass-data-submission/glass-data-submission-list/DataSubmissionList.tsx
  src/webapp/reports/glass-data-submission/glass-data-submission-list/Filters.tsx
Labels: small, waiting-for-review

#111 add auto complete compute report
  src/compositionRoot.ts
  src/data/common/DataSetD2Repository.ts
  src/data/common/DataValuesD2Repository.ts
  src/data/common/Dhis2ConfigRepository.ts
  src/data/common/Dhis2OrgUnitsRepository.ts
  src/data/reports/nhwa-auto-complete-compute/AutoCompleteComputeSettingsD2Repository.ts
  src/data/reports/nhwa-fix-totals/FixTotalsSettingsD2Repository.ts
  src/data/reports/nhwa-subnational-correct-orgunit/SubnationalCorrectD2Repository.ts
  src/data/reports/nhwa-subnational-correct-orgunit/SubnationalCorrectD2SettingsRepository.ts
  src/domain/common/entities/DataSet.ts
  src/domain/common/entities/DataValue.ts
  src/domain/common/entities/Stats.ts
  src/domain/common/repositories/DataSetRepository.ts
  src/domain/common/repositories/DataValuesRepository.ts
  src/domain/common/repositories/OrgUnitsRepository.ts
  src/domain/common/usecases/GetOrgUnitsByLevelUseCase.ts
  src/domain/reports/nhwa-auto-complete-compute/entities/AutoCompleteComputeSettings.ts
  src/domain/reports/nhwa-auto-complete-compute/repositores/AutoCompleteComputeSettingsRepository.ts
  src/domain/reports/nhwa-auto-complete-compute/usecases/FixAutoCompleteComputeValuesUseCase.ts
  src/domain/reports/nhwa-auto-complete-compute/usecases/GetAutoCompleteComputeValuesUseCase.ts
  src/domain/reports/nhwa-fix-totals/GetTotalsByActivityLevelUseCase.ts
  src/domain/reports/nhwa-fix-totals/entities/FixTotalsSettings.ts
  src/domain/reports/nhwa-fix-totals/repositories/FixTotalsSettingsRepository.ts
  src/domain/reports/nhwa-fix-totals/usecases/FixTotalsValuesUseCase.ts
  src/domain/reports/nhwa-subnational-correct-orgunit/entities/SubnationalCorrect.ts
  src/domain/reports/nhwa-subnational-correct-orgunit/repositories/SubnationalCorrectRepository.ts
  src/domain/reports/nhwa-subnational-correct-orgunit/repositories/SubnationalSettingsRepository.ts
  src/domain/reports/nhwa-subnational-correct-orgunit/usecases/DismissSubnationalCorrectValuesUseCase.ts
  src/domain/reports/nhwa-subnational-correct-orgunit/usecases/GetSubnationalCorrectUseCase.ts
  src/webapp/components/app/App.tsx
  src/webapp/reports/Reports.tsx
  src/webapp/reports/common/Filters.tsx
  src/webapp/reports/common/nhwa-settings.ts
  src/webapp/reports/nhwa-auto-complete-compute/NHWAAutoCompleteCompute.tsx
  src/webapp/reports/nhwa-fix-totals-activity-level/NHWAFixTotals.tsx
  src/webapp/reports/nhwa-subnational-correct-orgunit/NHWASubnationalCorrectOrgUnit.tsx
Labels: large, waiting-for-review

#117 fix: fix monitoring object issues
  src/domain/reports/mal-data-approval/entities/MalDataApprovalItem.ts
  src/webapp/reports/mal-data-approval/data-approval-list/DataApprovalList.tsx
Labels: small, waiting-for-review

#118 fix: make monitoring dataset object an array
  src/domain/reports/mal-data-approval/entities/MalDataApprovalItem.ts
  src/webapp/reports/mal-data-approval/data-approval-list/DataApprovalList.tsx
Labels: small, waiting-for-review

#103 feat: copy questionnaire dataset on approval
  src/data/reports/glass-data-submission/GLASSDataSubmissionDefaultRepository.ts
  src/domain/reports/glass-data-submission/entities/GLASSDataSubmissionItem.ts
Labels: small, waiting-for-review

#115 fix: egasp approval copies all events
  src/data/reports/glass-data-submission/GLASSDataSubmissionDefaultRepository.ts
Labels: small, waiting-for-review

#120 fix: make userGroup property an array
  src/domain/reports/mal-data-approval/entities/MalDataApprovalItem.ts
  src/webapp/reports/mal-data-approval/data-approval-list/DataApprovalList.tsx
Labels: small, waiting-for-review
